const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const RETRIEVE_PRODUCTS = 'RETRIEVE_PRODUCTS';
const ADD_PRODUCT = 'ADD_PRODUCT';
const ADD_TO_CART = 'ADD_TO_CART';
const UNDO = 'UNDO';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const REMOVE_ALL_FROM_CART = 'REMOVE_ALL_FROM_CART';
const SET_MESSAGE = 'SET_MESSAGE';

export {LOGIN, LOGOUT, RETRIEVE_PRODUCTS, ADD_PRODUCT, ADD_TO_CART, UNDO, REMOVE_FROM_CART, REMOVE_ALL_FROM_CART, SET_MESSAGE}
